title: F1 2025 points in different point systems
description: >
  F1 2025 Championship points in different point systems
baseurl: "/F1_2025_Different_Point_Systems"
url: "https://chrbeckm.github.io"
theme: minima
markdown: kramdown
