import numpy as np
from collections import defaultdict


def make_driver_dict(nr_of_races, dtype=np.int32):
    return defaultdict(lambda: np.zeros(nr_of_races + 1, dtype=dtype))


def get_point_systems_dict(nr_of_races, r_with, r_wo, grid, quali):
    point_systems = [
        {
            "name": "F1 A Raceresults with Sprints and DNF",
            "sprints": True,
            "dir": "withDNF_withSprint/formula1_extended/F1_A_B/A_r",
            "driver_dict": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_a": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_b": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "results": r_with,
        },
        {
            "name": "F1 A Raceresults without Sprints and with DNF",
            "sprints": False,
            "dir": "withDNF_woSprint/formula1_extended/F1_A_B/A_r",
            "driver_dict": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_a": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_b": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "results": r_with,
        },
        {
            "name": "F1 A Raceresults without Sprints and DNF",
            "sprints": False,
            "dir": "woDNF_woSprint/formula1_extended/F1_A_B/A_r",
            "driver_dict": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_a": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_b": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "results": r_wo,
        },
        {
            "name": "F1 A Raceresults with Sprints and without DNF",
            "sprints": True,
            "dir": "woDNF_withSprint/formula1_extended/F1_A_B/A_r",
            "driver_dict": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_a": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_b": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "results": r_wo,
        },
        {
            "name": "F1 A Gridresults with Sprints and DNF",
            "sprints": True,
            "dir": "withDNF_withSprint/formula1_extended/F1_A_B/A_q",
            "driver_dict": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_a": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_b": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "results": grid,
        },
        {
            "name": "F1 A Gridresults without Sprints and with DNF",
            "sprints": False,
            "dir": "withDNF_woSprint/formula1_extended/F1_A_B/A_q",
            "driver_dict": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_a": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_b": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "results": grid,
        },
        {
            "name": "F1 A Qualifyingresults without Sprints and DNF",
            "sprints": False,
            "dir": "woDNF_woSprint/formula1_extended/F1_A_B/A_q",
            "driver_dict": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_a": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_b": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "results": quali,
        },
        {
            "name": "F1 A Qualifyingresults with Sprints and without DNF",
            "sprints": True,
            "dir": "woDNF_withSprint/formula1_extended/F1_A_B/A_q",
            "driver_dict": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_a": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_b": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "results": quali,
        },
        {
            "name": "F1 B Raceresults with Sprints and DNF",
            "sprints": True,
            "dir": "withDNF_withSprint/formula1_extended/F1_A_B/B_r",
            "driver_dict": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_a": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_b": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "results": r_with,
        },
        {
            "name": "F1 B Raceresults without Sprints and with DNF",
            "sprints": False,
            "dir": "withDNF_woSprint/formula1_extended/F1_A_B/B_r",
            "driver_dict": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_a": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_b": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "results": r_with,
        },
        {
            "name": "F1 B Raceresults without Sprints and DNF",
            "sprints": False,
            "dir": "woDNF_woSprint/formula1_extended/F1_A_B/B_r",
            "driver_dict": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_a": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_b": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "results": r_wo,
        },
        {
            "name": "F1 B Raceresults with Sprints and without DNF",
            "sprints": True,
            "dir": "woDNF_withSprint/formula1_extended/F1_A_B/B_r",
            "driver_dict": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_a": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_b": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "results": r_wo,
        },
        {
            "name": "F1 B Gridresults with Sprints and DNF",
            "sprints": True,
            "dir": "withDNF_withSprint/formula1_extended/F1_A_B/B_q",
            "driver_dict": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_a": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_b": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "results": grid,
        },
        {
            "name": "F1 B Gridresults without Sprints and with DNF",
            "sprints": False,
            "dir": "withDNF_woSprint/formula1_extended/F1_A_B/B_q",
            "driver_dict": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_a": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_b": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "results": grid,
        },
        {
            "name": "F1 B Qualifyingresults without Sprints and DNF",
            "sprints": False,
            "dir": "woDNF_woSprint/formula1_extended/F1_A_B/B_q",
            "driver_dict": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_a": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_b": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "results": quali,
        },
        {
            "name": "F1 B Qualifyingresults with Sprints and without DNF",
            "sprints": True,
            "dir": "woDNF_withSprint/formula1_extended/F1_A_B/B_q",
            "driver_dict": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_a": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "driver_dict_b": defaultdict(lambda: np.zeros(nr_of_races + 1)),
            "results": quali,
        },
    ]
    return point_systems
