import numpy as np

scrabble_dict_eng = {
    "E": 1,
    "A": 1,
    "I": 1,
    "O": 1,
    "N": 1,
    "R": 1,
    "T": 1,
    "L": 1,
    "S": 1,
    "U": 1,
    "D": 2,
    "G": 2,
    "B": 3,
    "C": 3,
    "M": 3,
    "P": 3,
    "F": 4,
    "H": 4,
    "V": 4,
    "W": 4,
    "Y": 4,
    "K": 5,
    "J": 8,
    "X": 8,
    "Q": 10,
    "Z": 10,
}
scrabble_dict_ita = {
    "E": 1,
    "I": 1,
    "A": 1,
    "O": 1,
    "C": 2,
    "R": 2,
    "S": 2,
    "T": 2,
    "L": 3,
    "M": 3,
    "N": 3,
    "U": 3,
    "B": 5,
    "D": 5,
    "F": 5,
    "P": 5,
    "V": 5,
    "G": 8,
    "H": 8,
    "Z": 8,
    "Q": 10,
    "W": 0,
}
scrabble_dict_fra = {
    "L": 1,
    "N": 1,
    "O": 1,
    "R": 1,
    "S": 1,
    "T": 1,
    "U": 1,
    "I": 1,
    "A": 1,
    "E": 1,
    "G": 2,
    "D": 2,
    "M": 2,
    "B": 3,
    "C": 3,
    "P": 3,
    "F": 4,
    "H": 4,
    "V": 4,
    "J": 8,
    "Q": 8,
    "K": 10,
    "W": 10,
    "X": 10,
    "Y": 10,
    "Z": 10,
}
scrabble_dict_spa = {
    "L": 1,
    "T": 1,
    "N": 1,
    "R": 1,
    "U": 1,
    "I": 1,
    "S": 1,
    "O": 1,
    "A": 1,
    "E": 1,
    "G": 2,
    "D": 2,
    "B": 3,
    "M": 3,
    "P": 3,
    "C": 3,
    "F": 4,
    "V": 4,
    "Y": 4,
    "H": 4,
    "Q": 5,
    "J": 8,
    "X": 8,
    "Z": 10,
}
scrabble_dict_por = {
    "T": 1,
    "M": 2,
    "R": 1,
    "U": 1,
    "S": 1,
    "I": 1,
    "O": 1,
    "E": 1,
    "A": 1,
    "C": 2,
    "P": 2,
    "D": 2,
    "L": 2,
    "B": 3,
    "N": 3,
    "F": 4,
    "G": 4,
    "H": 4,
    "V": 4,
    "J": 5,
    "Q": 6,
    "X": 8,
    "Z": 8,
}
gp_s = [
    ("LOUISVUITTONAUSTRALI", scrabble_dict_eng),
    ("HEINEKENCHINESEGRAND", scrabble_dict_eng),
    ("HEINEKENCHINESEGRAND", scrabble_dict_eng),
    ("LENOVOJAPANESEGRANDP", scrabble_dict_eng),
    ("GULFAIRBAHRAINGRANDP", scrabble_dict_eng),
    ("STCSAUDIARABIANGRAND", scrabble_dict_eng),
    ("CRYPTOCOMMIAMIGRANDP", scrabble_dict_eng),
    ("CRYPTOCOMMIAMIGRANDP", scrabble_dict_eng),
    ("AWSGRANPREMIODELMADE", scrabble_dict_ita),
    ("TAGHEUERGRANDPRIXDEM", scrabble_dict_fra),
    ("ARAMCOGRANPREMIODEES", scrabble_dict_spa),
    ("PIRELLIGRANDPRIXDUCA", scrabble_dict_fra),
    ("MSCCRUISESAUSTRIANGR", scrabble_dict_eng),
    ("QATARAIRWAYSBRITISHG", scrabble_dict_eng),
    ("MOETCHANDONBELGIANGR", scrabble_dict_eng),
    ("MOETCHANDONBELGIANGR", scrabble_dict_eng),
    ("LENOVOHUNGARIANGRAND", scrabble_dict_eng),
    ("HEINEKENDUTCHGRANDPR", scrabble_dict_eng),
    ("PIRELLIGRANPREMIODIT", scrabble_dict_ita),
    ("QATARAIRWAYSAZERBAIJ", scrabble_dict_eng),
    ("SINGAPOREAIRLINESSIN", scrabble_dict_eng),
    ("MSCCRUISESUNITEDSTAT", scrabble_dict_eng),
    ("MSCCRUISESUNITEDSTAT", scrabble_dict_eng),
    ("GRANPREMIODELACIUDAD", scrabble_dict_spa),
    ("MSCCRUISESGRANDEPREM", scrabble_dict_eng),
    ("MSCCRUISESGRANDEPREM", scrabble_dict_por),
    ("HEINEKENLASVEGASGRAN", scrabble_dict_eng),
    ("QATARAIRWAYSQATARGRA", scrabble_dict_eng),
    ("QATARAIRWAYSQATARGRA", scrabble_dict_eng),
    ("ETIHADAIRWAYSABUDHAB", scrabble_dict_eng),
]
scrabble_list = np.zeros((len(gp_s), 20))
for j, (name, scrabble_dict) in enumerate(gp_s):
    splitlist = list(name)
    for i, ch in enumerate(splitlist):
        splitlist[i] = scrabble_dict[ch]
    scrabble_list[j] = splitlist
np.savetxt("helpfiles/scrabble.txt", scrabble_list, fmt="%.d")
